### ISSUE TITLE
Internal Server Error: /create/ -> while creating new article.

### ISSUE THREAD

**Issue by souravbadami** [betafactory/Artilizer#2]
```
Item no.: 1 --> Item name = initial  game  creating  zero  state
Evaluating...
Starting Download...
Completed Image ====> 1.MmZ3sTi.jpg

Errors: 0

Internal Server Error: /create/
Traceback (most recent call last):
  File "/Users/anonymous/.local/share/virtualenvs/Artilizer-83_qpuuw/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/anonymous/.local/share/virtualenvs/Artilizer-83_qpuuw/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/anonymous/.local/share/virtualenvs/Artilizer-83_qpuuw/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/anonymous/.local/share/virtualenvs/Artilizer-83_qpuuw/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/anonymous/Documents/opensource/betafactory/Artilizer/visualizer/views.py", line 181, in create
    summarize_text.append(" ".join(ranked_sentence[i][1]))
IndexError: list index out of range
[22/Sep/2019 16:46:05] "POST /create/ HTTP/1.1" 500 84486
```

**Article Text**: The game is a zero-player game, meaning that its evolution is determined by its initial state, requiring no further input. One interacts with the Game of Life by creating an initial configuration and observing how it evolves, or, for advanced players, by creating patterns with particular properties.

**Comment by srahulbadami** [comment]
Working on It !
